name: GitHub Actions

on:
  workflow_dispatch:
    
  schedule:
    - cron: "*/1  * * * *"
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install
      - run: npm run update-readme
        env:
          EMAIL_GMAIL: ${{ secrets.EMAIL_GMAIL }}
      - run: |
          git config user.name 'CarlosHawkers'
          git add README.md
          git add package-lock.json
          git commit -m "[bot] Update README"
          git push origin main



